# Generated by Django 5.1.1 on 2024-12-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_content_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog_content/'),
        ),
    ]
