# Generated by Django 5.1.1 on 2024-12-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_content_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.ImageField(default=1, upload_to='blog_content/'),
            preserve_default=False,
        ),
    ]
