# Generated by Django 5.1.1 on 2025-07-09 19:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_content_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('text_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='blog_content/')),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('quote', 'Quote'), ('link', 'Link'), ('image', 'Image'), ('heading', 'Heading'), ('sub_heading', 'Sub_Heading'), ('Mini_heading', 'Mini_Heading')], max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog_content/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
