# Generated by Django 5.1.1 on 2025-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cvcontent_alter_content_options_blog_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
